-- VUELTA (rollback): propiedad ecd_migrator -> postgres
-- Generado el 12-ago-2026 desde el inventario REAL de produccion.
-- Objetos propios del ECD unicamente: las 37 funciones de pgcrypto y las 4 de
-- plpgsql NO aparecen aqui a proposito, porque pertenecen a una extension y
-- moverlas rompe su vinculo con ella. Por eso no se usa REASSIGN OWNED.
-- Idempotente: ALTER ... OWNER TO sobre un objeto que ya pertenece al destino
-- no falla. Ejecutar dentro de UNA transaccion.

BEGIN;

ALTER SEQUENCE ai_brain."global_knowledge_id_seq" OWNER TO postgres;
ALTER SEQUENCE ai_brain."semantic_triples_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."activity_log_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."auth_events_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."companies_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."custom_attr_defs_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."daily_reports_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."dashboards_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."doc_reviews_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."doc_sets_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."element_docs_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."folder_permissions_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."gemelo_assets_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."gemelo_properties_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."geo_control_points_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."geo_model_georef_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."inventory_assets_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."job_titles_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."link_commands_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."lob_dataset_audit_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."lob_schedule_tasks_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."lob_schedule_tasks_v2_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."model_config_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."otp_codes_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."pdf_markups_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."photo_evidences_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."presupuesto_maestro_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."project_frentes_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."project_settings_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."projects_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."tracking_details_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."tracking_progress_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."transmittals_id_seq" OWNER TO postgres;
ALTER SEQUENCE public."users_id_seq" OWNER TO postgres;
ALTER TABLE ai_brain."feedback_buffer" OWNER TO postgres;
ALTER TABLE ai_brain."global_knowledge" OWNER TO postgres;
ALTER TABLE ai_brain."semantic_triples" OWNER TO postgres;
ALTER TABLE public."activity_log" OWNER TO postgres;
ALTER TABLE public."alembic_version" OWNER TO postgres;
ALTER TABLE public."app_tokens" OWNER TO postgres;
ALTER TABLE public."asset_user_data" OWNER TO postgres;
ALTER TABLE public."auth_events" OWNER TO postgres;
ALTER TABLE public."civil_alignments" OWNER TO postgres;
ALTER TABLE public."civil_base_axis" OWNER TO postgres;
ALTER TABLE public."civil_sections" OWNER TO postgres;
ALTER TABLE public."civil_surfaces" OWNER TO postgres;
ALTER TABLE public."companies" OWNER TO postgres;
ALTER TABLE public."control_pins" OWNER TO postgres;
ALTER TABLE public."custom_attr_defs" OWNER TO postgres;
ALTER TABLE public."custom_attr_values" OWNER TO postgres;
ALTER TABLE public."daily_reports" OWNER TO postgres;
ALTER TABLE public."dashboards" OWNER TO postgres;
ALTER TABLE public."doc_partidas" OWNER TO postgres;
ALTER TABLE public."doc_redlines" OWNER TO postgres;
ALTER TABLE public."doc_reviews" OWNER TO postgres;
ALTER TABLE public."doc_rfis" OWNER TO postgres;
ALTER TABLE public."doc_set_items" OWNER TO postgres;
ALTER TABLE public."doc_sets" OWNER TO postgres;
ALTER TABLE public."document_shares" OWNER TO postgres;
ALTER TABLE public."element_docs" OWNER TO postgres;
ALTER TABLE public."extraction_jobs" OWNER TO postgres;
ALTER TABLE public."file_nodes" OWNER TO postgres;
ALTER TABLE public."file_versions" OWNER TO postgres;
ALTER TABLE public."folder_permissions" OWNER TO postgres;
ALTER TABLE public."gemelo_assets" OWNER TO postgres;
ALTER TABLE public."gemelo_ingestion_status" OWNER TO postgres;
ALTER TABLE public."gemelo_properties" OWNER TO postgres;
ALTER TABLE public."geo_control_points" OWNER TO postgres;
ALTER TABLE public."geo_model_georef" OWNER TO postgres;
ALTER TABLE public."handoff_tickets" OWNER TO postgres;
ALTER TABLE public."hubs" OWNER TO postgres;
ALTER TABLE public."inventory_assets" OWNER TO postgres;
ALTER TABLE public."job_titles" OWNER TO postgres;
ALTER TABLE public."link_commands" OWNER TO postgres;
ALTER TABLE public."link_presence" OWNER TO postgres;
ALTER TABLE public."link_reports" OWNER TO postgres;
ALTER TABLE public."lob_activities" OWNER TO postgres;
ALTER TABLE public."lob_activity_relations" OWNER TO postgres;
ALTER TABLE public."lob_activity_schedule" OWNER TO postgres;
ALTER TABLE public."lob_avance" OWNER TO postgres;
ALTER TABLE public."lob_config" OWNER TO postgres;
ALTER TABLE public."lob_cost_items" OWNER TO postgres;
ALTER TABLE public."lob_dataset_audit" OWNER TO postgres;
ALTER TABLE public."lob_dataset_sources" OWNER TO postgres;
ALTER TABLE public."lob_datasets" OWNER TO postgres;
ALTER TABLE public."lob_element_links" OWNER TO postgres;
ALTER TABLE public."lob_frentes" OWNER TO postgres;
ALTER TABLE public."lob_front_map" OWNER TO postgres;
ALTER TABLE public."lob_linear_methodologies" OWNER TO postgres;
ALTER TABLE public."lob_linear_methodology_steps" OWNER TO postgres;
ALTER TABLE public."lob_linear_profiles" OWNER TO postgres;
ALTER TABLE public."lob_linear_progress_events" OWNER TO postgres;
ALTER TABLE public."lob_linear_resources" OWNER TO postgres;
ALTER TABLE public."lob_linear_scenarios" OWNER TO postgres;
ALTER TABLE public."lob_linear_zones" OWNER TO postgres;
ALTER TABLE public."lob_locations" OWNER TO postgres;
ALTER TABLE public."lob_partidas" OWNER TO postgres;
ALTER TABLE public."lob_progress_entries" OWNER TO postgres;
ALTER TABLE public."lob_schedule_tasks" OWNER TO postgres;
ALTER TABLE public."lob_schedule_tasks_v2" OWNER TO postgres;
ALTER TABLE public."model_config" OWNER TO postgres;
ALTER TABLE public."nomenclatura_config" OWNER TO postgres;
ALTER TABLE public."otp_codes" OWNER TO postgres;
ALTER TABLE public."pdf_calibrations" OWNER TO postgres;
ALTER TABLE public."pdf_markups" OWNER TO postgres;
ALTER TABLE public."photo_evidences" OWNER TO postgres;
ALTER TABLE public."presupuesto_maestro" OWNER TO postgres;
ALTER TABLE public."project_frentes" OWNER TO postgres;
ALTER TABLE public."project_settings" OWNER TO postgres;
ALTER TABLE public."project_users" OWNER TO postgres;
ALTER TABLE public."projects" OWNER TO postgres;
ALTER TABLE public."saved_views" OWNER TO postgres;
ALTER TABLE public."sensibilidad_catalogo" OWNER TO postgres;
ALTER TABLE public."sessions" OWNER TO postgres;
ALTER TABLE public."tracking_details" OWNER TO postgres;
ALTER TABLE public."tracking_pins" OWNER TO postgres;
ALTER TABLE public."tracking_progress" OWNER TO postgres;
ALTER TABLE public."transmittals" OWNER TO postgres;
ALTER TABLE public."triaje_seguridad" OWNER TO postgres;
ALTER TABLE public."upload_sessions" OWNER TO postgres;
ALTER TABLE public."users" OWNER TO postgres;
ALTER FUNCTION public.resolve_folder_path(p_path text, p_model_urn character varying, p_created_by character varying, p_auto_create boolean) OWNER TO postgres;
ALTER SCHEMA ai_brain OWNER TO postgres;
ALTER SCHEMA public   OWNER TO postgres;

COMMIT;