import assert from 'node:assert/strict';
import { normalizeInventoryPreload, normalizeInventoryRefresh } from '../src/lib/inventoryNormalizers.js';
import { inventoryEditPayload } from '../src/lib/inventoryIdentity.js';
import { calculateFilterResult, filterInventoryRows } from '../src/lib/filtersCore.js';
import { createFilterVisualDriver } from '../src/lib/filterVisualDriver.js';
import { facetItems, searchFacetItems } from '../src/lib/filterPresentation.js';
import { esPersistibleV2 } from '../src/lib/savedViewV2.js';
import { makeRuntimeFixture } from './filtersRuntime/fixture.mjs';
let text='';for await(const chunk of process.stdin) text+=chunk;
const {full,lite,saved}=JSON.parse(text);
const n=normalizeInventoryPreload(full,x=>x);
assert.deepEqual(n,normalizeInventoryRefresh(full,x=>x));
assert.deepEqual(new Set(n.mappedData.map(r=>r.element_key)),new Set(lite.map(r=>r.element_key)));
const urns=[...new Set(full.map(r=>r.source_urn))],ros=Object.fromEntries(urns.map(u=>[u,{}]));
for(const r of full) ros[r.source_urn][r.external_id]=1;
const state={scopeId:full[0].scope_id,schema:Object.values(n.schemaMap),filterProperties:Object.keys(n.schemaMap),filterSelections:{'G1::Estado':[full[0].properties.G1.Estado]},filterColors:{'G1::Estado':true}};
const result=calculateFilterResult(state,{scopeId:state.scopeId,rows:n.mappedData,rosetta:ros,datasetRevision:1,models:urns.map(modelUrn=>({modelUrn,ready:true}))},1);
assert.equal(result.status,'ready');
const expected=full.filter(r=>r.properties.G1.Estado===full[0].properties.G1.Estado).map(r=>r.element_key);
assert.deepEqual(result.matches.map(r=>r.rowKey),expected);
assert.deepEqual(filterInventoryRows(n.mappedData,result,state.scopeId).map(r=>r.element_key),expected);
assert.ok(searchFacetItems(facetItems(result.facets['G1::Estado'],[]),full[0].properties.G1.Estado).length);
const f=makeRuntimeFixture({count:1,sources:urns}),driver=createFilterVisualDriver({viewer:f.viewer,models:()=>f.models,window:f.host,yieldFrame:()=>Promise.resolve()});
await driver.apply(result,state,()=>true);
assert.equal(f.models.reduce((sum,m)=>sum+m.colors.size,0),expected.length);
assert.equal(esPersistibleV2(saved).ok,true);
driver.dispose();
console.log(JSON.stringify({pass:true,rows:full.length,matches:expected.length,edit:inventoryEditPayload(n.mappedData[0],'Status','B5 frontend write'),saved}));
